<?php

/**
 * @file
 * Module hooks for the Gutenberg example block.
 */

/**
 * Preprocess the example dynamic block.
 */
function template_preprocess_gutenberg_block__example__dynamic_block(&$variables) {
  // Dynamic block attribute.
  $variables['attributes']['data-example-dynamic-attribute'] = $variables['block_name'];
}

/**
 * Preprocess all blocks belonging to the 'example' namespace.
 *
 * Requires the gutenberg-block--example.html.twig template to exist.
 */
function template_preprocess_gutenberg_block__example(&$variables) {
  // Dynamic block attribute.
  $variables['attributes']['data-example-namespace-dynamic-attribute'] = 'true';
}
