widget_type.settings:
  type: config_object
  label: 'Widget Type config'
  mapping:
    download_assets:
      type: mapping
      mapping:
        allowed_list:
          type: sequence
          label: 'Enabled widget types'
          sequence:
            type: string
            label: 'Widget types'
            description: 'Widget type names or regular expressions to match them'
        disallowed_list:
          type: sequence
          label: 'Disabled widget types'
          sequence:
            type: string
            label: 'Widget types'
            description: 'Widget type names or regular expressions to match them'

widget_type.widget_registry_source.*:
  type: config_entity
  label: Widget Registry Source
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
    endpoint:
      type: string
