<?php

/**
 * @file
 * Provides an area_pizza entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function area_pizza_theme() {
  return [
    'area_pizza' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for area_pizza templates.
 *
 * Default template: area-pizza.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the area_pizza information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_area_pizza(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
