_core:
  default_config_hash: koZKG6ZJXEycSayM13ngD-P7IOXAlGoaJR_CyrYxL84
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  logo: true
  name: true
  node_user_picture: true
  slogan: true
facebook_url: 'https://www.facebook.com/zymphonies'
twitter_url: 'https://twitter.com/zymphonies'
linkedin_url: 'http://www.linkedin.com/company/zymphonies'
instagram_url: 'https://www.instagram.com/'
rss_url: rss.xml
show_social_icon: 1
show_credit_link: 1
show_slideshow: 1
slide_title_1: 'The Easiest Way to Get suitable Property'
slide_description_1: 'Find Flats, Apartments & Real Estate'
slide_url_1: '#'
slide_image_path_1: /images/slider/slide_01.jpg
